version: 0.0
os: linux
files:
  - source: /
    destination: /opt/app
hooks:
  BeforeInstall:
    - location: scripts/stop-server.sh
      timeout: 180
  AfterInstall:
    - location: scripts/start-server.sh
      timeout: 300
  ValidateService:
    - location: scripts/validate.sh
      timeout: 120
