name: Deploy Hybrid05 CICD Server

on:
  push:
    branches: [ staging ]   # 필요시 main으로 변경

env:
  AWS_REGION: ap-northeast-2
  IMAGE_TAG: ${{ github.sha }}                     # 커밋 SHA로 이미지 태그 고정
  S3_BUCKET: hybrid05-cicd-server                  # 배포 ZIP 저장 버킷
  S3_KEY: artifacts/${{ github.sha }}.zip          # ZIP 키(경로)

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Access Key 방식 (지금 secrets 쓰고 있으니 이대로 OK)
      - name: Configure AWS credentials (Access Key)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # OIDC 권장 방식(추후 교체 가능)
      # - name: Configure AWS credentials (OIDC)
      #   uses: aws-actions/configure-aws-credentials@v4
      #   with:
      #     role-to-assume: arn:aws:iam::<ACCOUNT_ID>:role/github-actions-deploy
      #     aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        # outputs.registry = <acct>.dkr.ecr.ap-northeast-2.amazonaws.com

      - name: Build & Push image (tag = commit SHA)
        env:
          ECR_REPO: ${{ steps.login-ecr.outputs.registry }}/hybrid05-server-registry
        run: |
          docker build -t "$ECR_REPO:${IMAGE_TAG}" .
          docker push "$ECR_REPO:${IMAGE_TAG}"

      - name: Make .env for compose (no hardcoded account id)
        env:
          ECR_REPO: ${{ steps.login-ecr.outputs.registry }}/hybrid05-server-registry
        run: |
          cat > .env <<EOF
          ECR_REPO=${ECR_REPO}
          IMAGE_TAG=${IMAGE_TAG}
          EOF
          cat .env

      - name: Fix permissions for scripts
        run: |
          chmod +x scripts/*.sh

      - name: Make deploy.zip (appspec + scripts + compose + .env)
        run: |
          zip -r deploy.zip appspec.yml scripts docker-compose.yml .env

      - name: Upload to S3
        run: aws s3 cp ./deploy.zip "s3://${S3_BUCKET}/${S3_KEY}"

      - name: Trigger CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name "hybrid05-cicd-server" \
            --deployment-group-name "Production" \
            --deployment-config-name "CodeDeployDefault.AllAtOnce" \
            --s3-location bucket=${S3_BUCKET},key=${S3_KEY},bundleType=zip
