name: Deploy Hybrid05 CICD Server

on:
  push:
    branches: [ main ]          # 필요하면 staging 으로 변경
  workflow_dispatch: {}         # 수동 실행 버튼

env:
  AWS_REGION: ap-northeast-2
  S3_BUCKET: hybrid05-cicd-server
  S3_KEY: artifacts/${{ github.sha }}.zip
  IMAGE_TAG: ${{ github.sha }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}                # ★ 중괄호 필수
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & Push image
        env:
          ECR_REPO: ${{ steps.login-ecr.outputs.registry }}/hybrid05-server-registry
        run: |
          docker build -t "$ECR_REPO:${IMAGE_TAG}" .
          docker push "$ECR_REPO:${IMAGE_TAG}"

      - name: Make .env for compose
        env:
          ECR_REPO: ${{ steps.login-ecr.outputs.registry }}/hybrid05-server-registry
        run: |
          cat > .env <<EOF
          ECR_REPO=${ECR_REPO}
          IMAGE_TAG=${IMAGE_TAG}
          EOF
          cat .env

      - name: Make deploy.zip
        run: |
          chmod +x scripts/*.sh
          zip -r deploy.zip appspec.yml scripts docker-compose.yml .env

      - name: Debug STS & S3 (who am I / bucket region / list)
        run: |
          echo "AWS_REGION=${{ env.AWS_REGION }}"
          echo "S3_BUCKET=${{ env.S3_BUCKET }}"
          echo "S3_KEY=${{ env.S3_KEY }}"
          echo "== STS get-caller-identity =="
          aws sts get-caller-identity
          echo "== S3 bucket location =="
          aws s3api get-bucket-location --bucket "${{ env.S3_BUCKET }}"
          echo "== S3 list prefix (may be empty on first run) =="
          aws s3 ls "s3://${{ env.S3_BUCKET }}/artifacts/" || true
          echo "== Head-bucket (permission check) =="
          aws s3api head-bucket --bucket "${{ env.S3_BUCKET }}" && echo "HEAD OK"


      - name: Upload to S3
        run: aws s3 cp ./deploy.zip "s3://${{ env.S3_BUCKET }}/${{ env.S3_KEY }}"

      - name: Trigger CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name "hybrid05-cicd-server" \
            --deployment-group-name "Production" \
            --deployment-config-name "CodeDeployDefault.AllAtOnce" \
            --s3-location bucket=${{ env.S3_BUCKET }},key=${{ env.S3_KEY }},bundleType=zip
